### PR TITLE
Fix several typos

### PR DESCRIPTION
**Pull request by Lonami**

### CODE REVIEW

**Comment by cfsamson** [comment]
Thanks for all the corrections. Are you sure `let’s` is more correct than `let's`? Just wondering, I don't even think I have a key for that type of apostrophe on my keyboard :)

**Comment by Lonami** [comment]
It's probably GitBook the one who added `’` instead of `'`. I personally would use the latter consistently, but since the first half of the book used `’`, I used that for consistency. Should I replace them all with `'`?

**Comment by cfsamson** [comment]
Hi. Ok, I see. Yeah, that would be great if you replaced them since I'll have a hard time doing edits having a character I don't have access to from the keyboard. I resolved some conflicts since I have done some updates lately to comments and code. Thanks for helping!

**Comment by cfsamson** [comment]
Thanks for all the corrections :)

**Comment by Lonami** [comment]
Thank you for merging :)

**Pull request merged**
